RooftopRepairs/Controllers/AboutUsController.cs
using Microsoft.AspNetCore.Mvc;
using RooftopRepairs.Interfaces;

namespace RooftopRepairs.Controllers
{
    public class AboutUsController : Controller
    {
        private readonly IFireService _fs;
        public AboutUsController(IFireService fs)
        {
            _fs = fs;
        }
        public IActionResult Index()
        {
            return View(_fs.getAboutUsImgs());
        }
    }
}

RooftopRepairs/Controllers/ContactsController.cs
using Microsoft.AspNetCore.Mvc;
using RooftopRepairs.Models;
using System.Net.Mail;
using System.Net;
using RooftopRepairs.Helpers;
using Google.Cloud.Firestore;
using NToastNotify;
using RooftopRepairs.Interfaces;

namespace RooftopRepairs.Controllers
{
    public class ContactsController : Controller
    {
        private readonly IEmailService _emailService;
        private readonly IToastNotification _toastNotification;
        public ContactsController(IEmailService emailSerice, IToastNotification toastNotification)
        {
            _emailService = emailSerice;
            _toastNotification = toastNotification;
        }
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Index(InquiryViewModel model)
        {
            Console.WriteLine(model.subject + '\n' + model.message);

            if (ModelState.IsValid)
            {
                _emailService.sendEmail(model);
                _toastNotification.AddSuccessToastMessage("Съобщението бе изпратено успешно");
                ModelState.Clear();
            } else _toastNotification.AddErrorToastMessage("Моля попълнете правилно всички полета");
            return Index();
        }
        
    }
}

RooftopRepairs/Controllers/GalleryController.cs
using Microsoft.AspNetCore.Mvc;
using RooftopRepairs.Interfaces;

namespace RooftopRepairs.Controllers
{
    public class GalleryController : Controller
    {
        private readonly IFireService _fs;
        public GalleryController(IFireService fs)
        {
            _fs = fs;
        }
        public IActionResult Roofs()
        {
            return View("Index", _fs.getRoofImgs());
        }

        public IActionResult Waterproofing()
        {
            return View("Index", _fs.getWaterproofingImgs());
        }
        public IActionResult Building()
        {
            return View("Index", _fs.getBuildingImgs());
        }
    }
}

RooftopRepairs/Controllers/ServicesController.cs
using Microsoft.AspNetCore.Mvc;
using NToastNotify;
using RooftopRepairs.Interfaces;
using RooftopRepairs.Models;
using System.ComponentModel;
using System.Dynamic;

namespace RooftopRepairs.Controllers
{
    public class ServicesController : Controller
    {
        private static readonly Dictionary<string, List<ServiceModel>> _model = new Dictionary<string, List<ServiceModel>>();
        private readonly IEmailService _emailService;
        private readonly IToastNotification _toastNotification;
        public ServicesController(IEmailService emailService, IToastNotification toastNotification)
        {
            _emailService = emailService;
            _toastNotification = toastNotification;
        }
        public IActionResult Index()
        {
            List<string> keys = new List<string>() { "Ремон на покриви и хидроизолация", "Тенекеджийство", "Изграждане на покриви", "Изграждане на комини", "Беседки и навеси" };
            List<ServiceModel> roofServices = new List<ServiceModel>() {
                new ServiceModel("Подмяна на керемиди", new List<string> { "Почистване на онсовата", "Полагане на покривно фолио", "Монтаж на самозалепващи битумни керемиди" }, "61,50", keys[0]),
                new ServiceModel("Пренареждане на керемиди", new List<string> { "Полагане на паропропусклива мембрана", "Монтаж на двоина скара от летви 4/3", "Редене на керемиди и капаци", "Измазване на капаци с варов циментов разтвор" }, "25,00", keys[0]),
                new ServiceModel("Смяна на стари керемиди", new List<string> { "Разкриване на старите елементи и почистване на основата", "Полагане на паропропусклива мембрана и монтаж на двоина скара от летви", "Редене на керемиди и капаци и измазване с варов циментов разтвор" }, "75,00", keys[0]),
                new ServiceModel("Хидроизолация", new List<string> { "Почистване и грундиране на основата, отстраняване на покривни язви", "Сваляне на филц от покрива или преместване от една страна на друга", "Почистване на старата хидроизолация и извозване на строителни отпадъци", "Залепване на хидроизолация със или без посипка" }, "45,00", keys[0])
            };
            List<ServiceModel> tinsmithingServices = new List<ServiceModel>() {
                new ServiceModel("Подмяна на капандури", new List<string> { "Демонтаж на стар улук", "Поставяне на скоби", "Монтаж на нов улук"}, "25,00", keys[1]),
                new ServiceModel("Подулучни и надулучни поли", new List<string> { "Демонтаж на стар улук", "Поставяне на скоби", "Монтаж на нов улук" }, "25,00", keys[1]),
                new ServiceModel("Подмяна на улуци", new List<string> { "Демонтаж на стар улук", "Поставяне на скоби", "Монтаж на нов улук" }, "25,00", keys[1]),
                new ServiceModel("Обшивки", new List<string> { "на комини", "на бордове", "подулучни/надулучни поли" }, "по договаряне", keys[1])
            };
            List<ServiceModel> buildingRoofs = new List<ServiceModel>() { 
                new ServiceModel("Нова покривна конструкция", new List<string> { "Демонтаж на старите керемиди, капаци, ламарини улуци и дървена конструкция", "Изграждане на нова конструкция с греди", "Оребяване на покрива", "Наковаване на дървена ламперия с дебелината на дъските", "Монтаж на Челни Дъски" }, "85,00", keys[2]),
                new ServiceModel("Надстройка на таванска стая", new List<string> { "Разкриване и почистване на старата конструкция", "Надзид на постройката", "Изграждане на нова конструкция", "Наковаване и лакиране на челни дъски", "Наковаване и лакиране на сачак", "Наковаване на дъсчена ламперия", "Извозване на отпадъци"}, "95,00", keys[2]),
                new ServiceModel("Сух монтаж на капаци", new List<string> { "Монтаж на билна летва", "Полагане на самозалепваща лента с алуминиево фолио", "Редене на капаци и захващане със винт и щипка за капак"}, "70,00", keys[2]),
                new ServiceModel("Изграждане на тухлен надзид", new List<string> { "С тухли четворка и варов циментов разтвор"}, "75,00", keys[2]),
                new ServiceModel("Изграждане на бетонен пояс", new List<string> { "Куфражни дъски", "Армировка от желязо", "Бетон Б 25"}, "75,00", keys[2]),
                
            };
            List<ServiceModel> buildingChimneys = new List<ServiceModel>() { 
                new ServiceModel("Измазване на комин", new List<string> { "С варов циментов разтвор" }, "По договаряне", keys[3]),
                new ServiceModel("Изграждане на бетонена шапка", new List<string> { "Куфражни дъски", "Армировка от желязо", "Бетон Б 25"}, "75,00", keys[3]),
            };
            List<ServiceModel> buildingGazebo = new List<ServiceModel>() { 
                new ServiceModel("Изграждане на беседка или навес", new List<string> { "Топлоизолация по желание" }, "По договаряне", keys[4])
            };

            _model[keys[0]] = roofServices;
            _model[keys[1]] = tinsmithingServices;
            _model[keys[2]] = buildingRoofs;
            _model[keys[3]] = buildingChimneys;
            _model[keys[4]] = buildingGazebo;
            
            return View(_model);
        }

        [HttpGet]
        public IActionResult Single(string id, string key)
        {
            ServiceModel single = null;

            single = _model[key].Where(i => i.id == id).FirstOrDefault();

            if (single is not null)
            {
                SingleServiceModel model = new SingleServiceModel(single, new InquiryViewModel(single.serviceName));
                return View(model);
            }
            else
            {
                _toastNotification.AddErrorToastMessage("Нещо се обърка");
                return Index();
            }
        }
        [HttpPost]
        public IActionResult Inquire(SingleServiceModel mod)
        {
            if (ModelState.IsValid)
            {
                _emailService.sendEmail(mod.inquiry);
                _toastNotification.AddSuccessToastMessage("Съобщението бе изпратено успешно");
                mod.inquiry.clear();
            } else _toastNotification.AddErrorToastMessage("Моля попълнете правилно всички полета");
            return RedirectToAction("Single", new { mod.service.id, mod.service.key });
        }
    }
}

RooftopRepairs/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RooftopRepairs</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Serif:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,200&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/RooftopRepairs.styles.css" asp-append-version="true" />
    <script async src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC3WiDCIyXHC6oF_P3P7MjwxRhNdb3u6_4&callback=console.debug&libraries=maps,marker&v=beta">
    </script>
    <script src="https://kit.fontawesome.com/01a57c0a85.js" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</head>
<body class="px-0">
    <header>
        <!--Top bar-->
        <section class="top-bar">
            <div class="row text-light px-3" style="width:100%; height:100%; ">
                <div class="col-sm pl-5">
                    tesla.rooftop.repair@gmail.com
                </div><div class="col-md-6 text-center">
                    <!--Brand-->
                    <a class="navbar-brand text-light" asp-area="" asp-controller="Home" asp-action="Index">ТЕСЛА ЕООД</a>
                </div>
                      <a class="col-sm pr-5 text-end" href="tel:+359883686966" style="color: white;">
                    +359&nbsp;883&nbsp;68&nbsp;69&nbsp;66&nbsp;
                      </a>
            </div>
        </section>
        <!-- Navbar -->
        <nav class="navbar navbar-dark navbar-expand-lg fixed-top">
            <div class="container" style="width: 100%">
                <!-- Toggler -->
                <button class="navbar-toggler border-0 shadow-none" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="sidebar offcanvas offcanvas-start" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
                    <div class="offcanvas-header">
                        <h5 class="offcanvas-title text-light display-5" id="offcanvasNavbarLabel">ТЕСЛА ЕООД</h5>
                        <button type="button" class="btn-close btn-close-white border-0 shadow-none" data-bs-dismiss="offcanvas" aria-label="Close"></button>
                    </div>
                    <div class="offcanvas-body">
                        <ul class="navbar-nav justify-content-around flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">НАЧАЛО</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="AboutUs" asp-action="Index">ЗА НАС</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Services" asp-action="Index">УСЛУГИ</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Gallery" asp-action="Roofs">ГАЛЕРИЯ</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Contacts" asp-action="Index">КОНТАКТИ</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </nav>
    </header>

    <!--Body-->
    <div class="d-flex justify-content-center">
        <div class="global-wrapper text-center">
            <main role="main">
                @RenderBody()
            </main>
        </div>
    </div>

    <!--Footer-->
    <footer class="border-top footer text-white">
        <div class="container">
            &copy; 2023 - ТЕСЛА ЕООД - Website courtesy of atanas.p.atanasov.2003@gmail.com
        </div>
    </footer>



    <script src="/_framework/aspnetcore-browser-refresh.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    @await Component.InvokeAsync("NToastNotify")
</body>
</html>